"""add employee_code and reset token columns

Revision ID: f89c8a0575fd
Revises: 4cb7e89a4890
Create Date: 2026-08-10 10:14:10.442218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89c8a0575fd'
down_revision: Union[str, Sequence[str], None] = '4cb7e89a4890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['employee_code'])
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'employee_code')
    # ### end Alembic commands ###
